#! /bin/sh

xrdb $HOME/.Xresources
feh --bg-scale $HOME/Downloads/my-wallpaper.jpg

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1-1 -d I
bspc monitor HDMI-0 -d  II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
