#! /bin/sh

xrdb $HOME/.Xresources
feh --bg-scale $HOME/Downloads/my-wallpaper.jpg

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1-1 -d 1
bspc monitor HDMI-0 -d  2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config bottom_padding	0
bspc config right_padding	0

# Border
bspc config focused_border_color        "#c792ea"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

$HOME/.config/polybar/launch.sh
