# i3status configuration file
# see "man i3status" for documentation

general {
        colors = true
        interval = 5
        output_format = "none"
        separator = "|||"
        color_good = "#00FF88"
        color_degraded = "#FFAA00"
        color_bad = "#FF0044"
        color_separator = "#9B30FF"
}

order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "disk /"
order += "load"
order += "memory"
order += "tztime local"
order += "volume master"

wireless _first_ {
        format_up = " (%quality at %essid) %ip"
        format_down = " down"
}

ethernet _first_ {
        format_up = " %ip (%speed)"
        format_down = " down"
}

battery all {
        format = " %status %percentage %remaining"
}

disk "/" {
        format = " %avail"
}

load {
        format = " %1min"
}

memory {
        format = " %used | %available"
        threshold_degraded = "1G"
        format_degraded = " MEMORY < %available"
}

tztime local {
        format = " %Y-%m-%d %H:%M:%S"
}

volume master {
        format = " %volume"
        format_muted = " muted (%volume)"
        device = "default"
        mixer = "Master"
}
